url: https://y7kim.github.io
baseurl: /bottegastudente/

# Site settings
title: Bottega dello Studente
email: bottegadellostudente@gmail.com
description: "Bottega dello Studente, cartolibreria nel centro storico di Cagliari, dal 1938."


# Team names, titles and social links
people:
- name: Francesco Mancosu
  pic: 1
  position: Proprietario
  social:
    - title: facebook
      url: https://www.facebook.com/BottegaDelloStudente
- name: Marta Mancosu
  pic: 2
  position: Social Media Manager
  social:
    - title: twitter
      url: https://twitter.com/martamancosu
    - title: facebook
      url: https://www.facebook.com/martaman
    - title: instagram
      url: https://www.instagram.com/tappinacaffuta/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
